config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    member do
      get 'share'
    end
  end
  get 'shared/:share_token', to: 'documents#shared', as: 'document_share'
  
  devise_for :users
  root 'documents#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  mount_uploader :file, FileUploader

  validates :name, presence: true
  validates :file, presence: true

  before_create :generate_share_token

  private

  def generate_share_token
    self.share_token = SecureRandom.urlsafe_base64
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :documents, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
  
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
    private
  
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
  end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!, except: [:shared]
  before_action :set_document, only: [:show, :edit, :update, :destroy, :share]

  def index
    @documents = policy_scope(Document)
  end

  def show
    authorize @document
  end

  def new
    @document = current_user.documents.new
    authorize @document
  end

  def create
    @document = current_user.documents.new(document_params)
    authorize @document

    if @document.save
      redirect_to @document, notice: 'Document was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @document
  end

  def update
    authorize @document
    if @document.update(document_params)
      redirect_to @document, notice: 'Document was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @document
    @document.destroy
    redirect_to documents_url, notice: 'Document was successfully destroyed.'
  end

  def share
    authorize @document
    @share_url = document_share_url(@document.share_token)
  end

  def shared
    @document = Document.find_by!(share_token: params[:share_token])
    render :preview
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:name, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>Name:</strong>
    <%= document.name %>
  </p>

  <p>
    <strong>File:</strong>
    <%= document.file %>
  </p>

  <p>
    <strong>User:</strong>
    <%= document.user_id %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= simple_form_for(@document) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :file, as: :file %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Documents</h1>

<div id="documents">
  <% @documents.each do |document| %>
    <%= render document %>
    <p>
      <%= link_to "Show this document", document %>
    </p>
  <% end %>
</div>

<%= link_to "New document", new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/preview.html.erb
<h1>Document Preview: <%= @document.name %></h1>

<div class="document-preview">
  <% if @document.file.content_type.start_with?('image') %>
    <%= image_tag @document.file.url, class: 'preview-image' %>
  <% elsif @document.file.content_type == 'application/pdf' %>
    <embed src="<%= @document.file.url %>" type="application/pdf" width="100%" height="600px" />
  <% elsif @document.file.content_type.start_with?('text') %>
    <pre><%= File.read(@document.file.path) %></pre>
  <% else %>
    <p>Preview not available for this file type. <%= link_to 'Download', @document.file.url %></p>
  <% end %>
</div>

app/views/documents/share.html.erb
<h1>Share Document</h1>
<p>Share this URL: <%= link_to @share_url, @share_url %></p>
<p>Preview URL: <%= link_to 'Preview Document', @share_url %></p>

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @document %>

<div>
  <%= link_to 'Share', share_document_path(@document), class: 'btn btn-primary' %>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dropbox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>